from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

from .model import Component


LANGUAGE_BY_SUFFIX = {
    ".py": "python", ".pyi": "python", ".js": "javascript", ".jsx": "javascript",
    ".ts": "typescript", ".tsx": "typescript", ".cs": "csharp", ".fs": "fsharp",
    ".java": "java", ".kt": "kotlin", ".go": "go", ".rs": "rust", ".rb": "ruby",
    ".php": "php", ".c": "c", ".h": "c", ".cpp": "cpp", ".cc": "cpp", ".hpp": "cpp",
    ".swift": "swift", ".lua": "lua", ".ps1": "powershell", ".sh": "shell", ".bash": "shell",
    ".sql": "sql", ".html": "html", ".css": "css", ".scss": "css", ".md": "markdown",
    ".rst": "documentation", ".yml": "yaml", ".yaml": "yaml", ".toml": "toml", ".json": "json", ".xml": "xml",
}

IGNORE_DIRS = {
    ".git", ".hg", ".svn", ".idea", ".vscode", "node_modules", "vendor", ".venv", "venv", "env",
    "dist", "build", "target", "bin", "obj", ".next", ".nuxt", ".pytest_cache", ".mypy_cache",
    ".ruff_cache", "coverage", ".coverage", "__pycache__",
}

GENERATED_MARKERS = ("generated file", "auto-generated", "autogenerated", "do not edit", "code generated", "generated by")

IMPORT_PATTERNS: dict[str, tuple[re.Pattern[str], ...]] = {
    "python": (re.compile(r"^\s*from\s+([\w.]+)\s+import\s+", re.M), re.compile(r"^\s*import\s+([\w.]+)", re.M)),
    "javascript": (re.compile(r"(?:from\s+|require\s*\(\s*)['\"]([^'\"]+)['\"]", re.M), re.compile(r"^\s*import\s+['\"]([^'\"]+)['\"]", re.M)),
    "typescript": (re.compile(r"(?:from\s+|require\s*\(\s*)['\"]([^'\"]+)['\"]", re.M), re.compile(r"^\s*import\s+['\"]([^'\"]+)['\"]", re.M)),
    "csharp": (re.compile(r"^\s*using\s+([\w.]+)\s*;", re.M),),
    "fsharp": (re.compile(r"^\s*open\s+([\w.]+)", re.M),),
    "java": (re.compile(r"^\s*import\s+([\w.]+)", re.M),),
    "kotlin": (re.compile(r"^\s*import\s+([\w.]+)", re.M),),
    "go": (re.compile(r'^\s*"([^\"]+)"\s*$', re.M),),
    "rust": (re.compile(r"^\s*(?:use|mod)\s+([\w:]+)", re.M),),
}


@dataclass(slots=True)
class ScannedFile:
    component: Component
    text: str


def _is_binary(data: bytes) -> bool:
    if b"\x00" in data[:4096]:
        return True
    if not data:
        return False
    sample = data[:4096]
    bad = sum(1 for b in sample if b < 9 or (13 < b < 32))
    return bad / max(1, len(sample)) > 0.05


def _code_lines(text: str, language: str) -> int:
    count = 0
    in_block = False
    for raw in text.splitlines():
        line = raw.strip()
        if not line:
            continue
        if language in {"c", "cpp", "csharp", "java", "javascript", "typescript", "kotlin", "swift"}:
            if in_block:
                if "*/" in line:
                    in_block = False
                continue
            if line.startswith("/*"):
                if "*/" not in line:
                    in_block = True
                continue
            if line.startswith("//"):
                continue
        elif language in {"python", "ruby", "powershell", "shell"} and line.startswith("#"):
            continue
        count += 1
    return count


def _imports(text: str, language: str) -> list[str]:
    found: list[str] = []
    for pattern in IMPORT_PATTERNS.get(language, ()):
        found.extend(match.group(1) for match in pattern.finditer(text))
    return sorted(set(found))


def scan_repository(root: Path, max_file_bytes: int = 1_000_000) -> list[ScannedFile]:
    root = root.resolve()
    scanned: list[ScannedFile] = []
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        relative = path.relative_to(root)
        if any(part in IGNORE_DIRS for part in relative.parts):
            continue
        language = LANGUAGE_BY_SUFFIX.get(path.suffix.lower())
        if language is None:
            continue
        try:
            data = path.read_bytes()
        except (OSError, PermissionError):
            continue
        if len(data) > max_file_bytes or _is_binary(data):
            continue
        text = data.decode("utf-8", errors="replace")
        if any(marker in text[:2000].lower() for marker in GENERATED_MARKERS):
            continue
        component = Component(
            path=relative.as_posix(), language=language, lines=len(text.splitlines()),
            code_lines=_code_lines(text, language), bytes=len(data), imports=_imports(text, language),
        )
        scanned.append(ScannedFile(component=component, text=text))
    return scanned
