from __future__ import annotations

import ast
import io
import re
import tokenize
from dataclasses import dataclass
from pathlib import Path

from .model import Component


LANGUAGE_BY_SUFFIX = {
    ".py": "python", ".pyi": "python", ".js": "javascript", ".jsx": "javascript",
    ".ts": "typescript", ".tsx": "tsx", ".cs": "csharp", ".fs": "fsharp",
    ".java": "java", ".kt": "kotlin", ".go": "go", ".rs": "rust", ".rb": "ruby",
    ".php": "php", ".c": "c", ".h": "c", ".cpp": "cpp", ".cc": "cpp", ".hpp": "cpp",
    ".swift": "swift", ".lua": "lua", ".ps1": "powershell", ".sh": "shell", ".bash": "shell",
    ".sql": "sql", ".html": "html", ".css": "css", ".scss": "css", ".md": "markdown",
    ".rst": "documentation", ".yml": "yaml", ".yaml": "yaml", ".toml": "toml", ".json": "json", ".xml": "xml",
}

IGNORE_DIRS = {
    ".git", ".hg", ".svn", ".idea", ".vscode", "node_modules", "vendor", ".venv", "venv", "env",
    "dist", "build", "target", "bin", "obj", ".next", ".nuxt", ".pytest_cache", ".mypy_cache",
    ".ruff_cache", "coverage", ".coverage", "__pycache__",
}

GENERATED_MARKERS = ("generated file", "auto-generated", "autogenerated", "do not edit", "code generated", "generated by")
_COMMENTISH_HEADER_PREFIXES = ("#", "//", "/*", "*", "<!--", ";", "--")

IMPORT_PATTERNS: dict[str, tuple[re.Pattern[str], ...]] = {
    "python": (re.compile(r"^\s*from\s+([\w.]+)\s+import\s+", re.M), re.compile(r"^\s*import\s+([\w.]+)", re.M)),
    "javascript": (re.compile(r"(?:from\s+|require\s*\(\s*)['\"]([^'\"]+)['\"]", re.M), re.compile(r"^\s*import\s+['\"]([^'\"]+)['\"]", re.M)),
    "typescript": (re.compile(r"(?:from\s+|require\s*\(\s*)['\"]([^'\"]+)['\"]", re.M), re.compile(r"^\s*import\s+['\"]([^'\"]+)['\"]", re.M)),
    "tsx": (re.compile(r"(?:from\s+|require\s*\(\s*)['\"]([^'\"]+)['\"]", re.M), re.compile(r"^\s*import\s+['\"]([^'\"]+)['\"]", re.M)),
    "csharp": (re.compile(r"^\s*using\s+([\w.]+)\s*;", re.M),),
    "fsharp": (re.compile(r"^\s*open\s+([\w.]+)", re.M),),
    "java": (re.compile(r"^\s*import\s+([\w.]+)", re.M),),
    "kotlin": (re.compile(r"^\s*import\s+([\w.]+)", re.M),),
    "go": (re.compile(r'^\s*"([^\"]+)"\s*$', re.M),),
    "rust": (re.compile(r"^\s*(?:use|mod)\s+([\w:]+)", re.M),),
}


@dataclass(slots=True)
class ScannedFile:
    component: Component
    text: str


def _is_binary(data: bytes) -> bool:
    if b"\x00" in data[:4096]:
        return True
    if not data:
        return False
    sample = data[:4096]
    bad = sum(1 for b in sample if b < 9 or (13 < b < 32))
    return bad / max(1, len(sample)) > 0.05


def _python_non_code_lines(text: str, lines: list[str] | None = None) -> set[int]:
    non_code: set[int] = set()
    lines = text.splitlines() if lines is None else lines
    try:
        tokens = tokenize.generate_tokens(io.StringIO(text).readline)
        for token in tokens:
            if token.type == tokenize.COMMENT:
                line_no, col = token.start
                if not lines[line_no - 1][:col].strip():
                    non_code.add(line_no)
    except (tokenize.TokenError, IndentationError):
        pass

    try:
        tree = ast.parse(text)
    except (SyntaxError, ValueError, RecursionError):
        return non_code

    def mark_docstring(body: list[ast.stmt]) -> None:
        if body:
            first = body[0]
            if isinstance(first, ast.Expr) and isinstance(first.value, ast.Constant) and isinstance(first.value.value, str):
                start = int(getattr(first, "lineno", 1) or 1)
                end = int(getattr(first, "end_lineno", start) or start)
                non_code.update(range(start, end + 1))
        for node in body:
            if isinstance(node, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)):
                mark_docstring(node.body)

    mark_docstring(tree.body)
    return non_code


def _code_lines(text: str, language: str, lines: list[str] | None = None) -> int:
    lines = text.splitlines() if lines is None else lines
    python_non_code = _python_non_code_lines(text, lines) if language == "python" else set()
    c_block_languages = {"c", "cpp", "csharp", "java", "javascript", "typescript", "tsx", "kotlin", "swift", "go", "rust", "php", "css"}
    slash_comment_languages = c_block_languages | {"scss"}
    hash_comment_languages = {"python", "ruby", "powershell", "shell", "yaml", "toml", "php"}
    dash_comment_languages = {"sql", "lua"}

    count = 0
    in_block = False
    for line_number, raw in enumerate(lines, 1):
        line = raw.strip()
        if not line:
            continue
        if language == "python" and line_number in python_non_code:
            continue
        if language in c_block_languages:
            if in_block:
                if "*/" in line:
                    in_block = False
                continue
            if line.startswith("/*"):
                if "*/" not in line:
                    in_block = True
                continue
        if language in slash_comment_languages and line.startswith("//"):
            continue
        if language in hash_comment_languages and line.startswith("#"):
            continue
        if language in dash_comment_languages and line.startswith("--"):
            continue
        if language in {"html", "xml"} and line.startswith("<!--") and line.endswith("-->"):
            continue
        count += 1
    return count


def _imports(text: str, language: str) -> list[str]:
    found: list[str] = []
    for pattern in IMPORT_PATTERNS.get(language, ()):
        found.extend(match.group(1) for match in pattern.finditer(text))
    return sorted(set(found))


def _looks_generated(text: str, lines: list[str] | None = None) -> bool:
    lines = text.splitlines() if lines is None else lines
    for raw in lines[:12]:
        line = raw.strip().lower()
        if not line or not line.startswith(_COMMENTISH_HEADER_PREFIXES):
            continue
        if any(marker in line for marker in GENERATED_MARKERS):
            return True
    return False


def scan_repository(
    root: Path,
    max_file_bytes: int = 1_000_000,
    *,
    warnings: list[str] | None = None,
) -> list[ScannedFile]:
    root = root.resolve()
    scanned: list[ScannedFile] = []
    generated_skipped = 0
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        relative = path.relative_to(root)
        if any(part in IGNORE_DIRS for part in relative.parts):
            continue
        language = LANGUAGE_BY_SUFFIX.get(path.suffix.lower())
        if language is None:
            continue
        try:
            data = path.read_bytes()
        except (OSError, PermissionError):
            continue
        if len(data) > max_file_bytes or _is_binary(data):
            continue
        text = data.decode("utf-8", errors="replace")
        lines = text.splitlines()
        if _looks_generated(text, lines):
            generated_skipped += 1
            continue
        component = Component(
            path=relative.as_posix(), language=language, lines=len(lines),
            code_lines=_code_lines(text, language, lines), bytes=len(data), imports=_imports(text, language),
        )
        scanned.append(ScannedFile(component=component, text=text))
    if warnings is not None and generated_skipped:
        warnings.append(f"Skipped {generated_skipped} file(s) with generated-code markers in their header.")
    return scanned
