from __future__ import annotations

import json

import pytest

from ouroboros.classify import classify
from ouroboros.config import Config
from ouroboros.graph import resolve_dependencies
from ouroboros.model import Category, Component
from ouroboros.scanner import ScannedFile, _code_lines, _looks_generated
from ouroboros.semantic import EdgeKind, Resolution, build_semantic_graph
from ouroboros.semantic.adapters import AdapterRegistry, TREE_SITTER_LANGUAGE_KEYS
from ouroboros.semantic.graph import finalize_graph
from ouroboros.semantic.model import SemanticEdge, SemanticGraph, Symbol, SymbolKind


def scanned(path: str, text: str, category: Category = Category.UNKNOWN, language: str = "python") -> ScannedFile:
    return ScannedFile(
        Component(path=path, language=language, lines=max(1, len(text.splitlines())),
                  code_lines=max(1, len(text.splitlines())), bytes=len(text.encode()), category=category),
        text,
    )


def test_unknown_is_reachable_and_short_keywords_need_boundaries():
    assert classify(scanned("plain.py", "x = 1\n")).category == Category.UNKNOWN
    result = classify(scanned("src/building.py", "decimal = 'placid'\n"))
    assert result.category not in {Category.USER_SURFACE, Category.PROCESS_MACHINERY}


def test_dot_prefixed_paths_are_preserved():
    cfg = Config(ignore=("gitignore",), overrides={".github": Category.PROCESS_MACHINERY})
    assert not cfg.ignored(".gitignore")
    assert cfg.category_for(".github/workflows/test.yml") == Category.PROCESS_MACHINERY


def test_generated_marker_requires_comment_header_and_python_docstrings_are_not_code():
    assert _looks_generated("# generated by tool\nprint('x')\n")
    assert not _looks_generated("print('this text says generated by a tool')\n")
    text = '\n"""module docs"""\n# comment\nx = 1\n\ndef f():\n    """function docs"""\n    # comment\n    return x\n'
    assert _code_lines(text, "python") == 3


def test_baseline_dependency_tail_match_is_boundary_safe():
    components = [
        Component("src/on.py", "python", 1, 1, 1),
        Component("src/app.py", "python", 1, 1, 1, imports=["json"]),
    ]
    assert resolve_dependencies(components)["src/app.py"] == set()


def test_real_import_binding_is_exact_but_bare_cross_file_name_is_probable():
    graph = build_semantic_graph([
        scanned("app.py", "from physics import resolve\ndef run():\n    return resolve()\n", Category.CORE_PRODUCT),
        scanned("physics.py", "def resolve():\n    return 1\n", Category.ESSENTIAL_SUPPORT),
    ], file_dependencies={"app.py": {"physics.py"}, "physics.py": set()})
    call = next(e for e in graph.edges if e.kind == EdgeKind.CALLS and e.target_name == "physics.resolve")
    assert call.resolution == Resolution.EXACT

    graph = build_semantic_graph([
        scanned("app.py", "def run():\n    return helper()\n", Category.CORE_PRODUCT),
        scanned("helper.py", "def helper():\n    return 1\n", Category.ESSENTIAL_SUPPORT),
    ])
    call = next(e for e in graph.edges if e.kind == EdgeKind.CALLS and e.target_name == "helper")
    assert call.resolution == Resolution.PROBABLE


def test_isoupdater_path_resolve_regression_and_mixed_file_roles():
    files = [
        scanned(
            "iso_manager.py",
            "from pathlib import Path\n"
            "class IntegrityStore:\n"
            "    def verify(self, path):\n        return path\n"
            "class LibraryInspector:\n"
            "    def unmatched(self, path):\n        return Path(path).resolve()\n"
            "    def images(self):\n        return []\n",
            Category.VERIFICATION,
        ),
        scanned(
            "iso_updater.py",
            "class ISOScanner:\n"
            "    def resolve_updates(self):\n"
            "        def resolve():\n            return 1\n"
            "        return resolve()\n",
            Category.CORE_PRODUCT,
        ),
    ]
    graph = build_semantic_graph(files)
    bogus = [
        e for e in graph.edges
        if e.kind == EdgeKind.CALLS and e.target_name == "pathlib.Path.resolve"
        and e.resolution == Resolution.EXACT and e.target_id
        and "resolve_updates.resolve" in e.target_id
    ]
    assert bogus == []
    by_name = {s.qualified_name: s for s in graph.symbols.values()}
    assert by_name["IntegrityStore.verify"].category == Category.VERIFICATION
    assert by_name["LibraryInspector.images"].category == Category.ESSENTIAL_SUPPORT


def test_file_dependency_cannot_fabricate_unrelated_exact_import():
    graph = build_semantic_graph([
        scanned("app.py", "import os\ndef run():\n    return os.getcwd()\n", Category.CORE_PRODUCT),
        scanned("physics.py", "def resolve():\n    return 1\n", Category.ESSENTIAL_SUPPORT),
    ], file_dependencies={"app.py": {"physics.py"}, "physics.py": set()})
    edge = next(e for e in graph.edges if e.kind == EdgeKind.IMPORTS)
    assert edge.resolution != Resolution.EXACT
    assert edge.target_id is None or "physics.py" not in edge.target_id


def test_chain_budget_and_zero_product_ratio_are_explicit_json():
    product = Symbol(id="app.py::run@1", path="app.py", language="python", kind=SymbolKind.FUNCTION,
                     name="run", qualified_name="run", start_line=1, end_line=1, category=Category.CORE_PRODUCT)
    symbols = {product.id: product}
    edges = []
    for index in range(20):
        symbol = Symbol(id=f"audit{index}.py::check@1", path=f"audit{index}.py", language="python",
                        kind=SymbolKind.FUNCTION, name=f"check{index}", qualified_name=f"check{index}",
                        start_line=1, end_line=1, category=Category.AUDIT_PROVENANCE)
        symbols[symbol.id] = symbol
        edges.append(SemanticEdge(source_id=symbol.id, kind=EdgeKind.CALLS, target_name="run",
                                  target_id=product.id, resolution=Resolution.EXACT))
    graph = finalize_graph(SemanticGraph(symbols=symbols, edges=edges), max_chain_expansions=3)
    assert graph.chain_truncated and graph.metrics and graph.metrics.chain_expansions == 3

    audit = Symbol(id="audit.py::check@1", path="audit.py", language="python", kind=SymbolKind.FUNCTION,
                   name="check", qualified_name="check", start_line=1, end_line=1,
                   category=Category.AUDIT_PROVENANCE)
    graph = finalize_graph(SemanticGraph(symbols={audit.id: audit}))
    assert graph.metrics and graph.metrics.scaffolding_symbol_ratio is None
    json.dumps(graph.to_dict(), allow_nan=False)


def test_adapter_failure_is_isolated():
    class BrokenAdapter:
        def supports(self, language: str) -> bool: return language == "python"
        def parse(self, item): raise RuntimeError("boom")

    graph = build_semantic_graph([scanned("a.py", "x=1", Category.CORE_PRODUCT)],
                                 registry=AdapterRegistry([BrokenAdapter()]))
    assert graph.metrics is not None
    assert any(d.severity == "error" and "boom" in d.message for d in graph.diagnostics)


def test_every_declared_tree_sitter_parser_key_loads():
    pack = pytest.importorskip("tree_sitter_language_pack")
    for language, key in TREE_SITTER_LANGUAGE_KEYS.items():
        assert pack.get_parser(key) is not None, f"{language} -> {key}"
